/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package abacus.api.query;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SelectionMode implements org.apache.thrift.TEnum {
  SHOULD(0),
  MUST(1),
  MUST_NOT(2);

  private final int value;

  private SelectionMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SelectionMode findByValue(int value) { 
    switch (value) {
      case 0:
        return SHOULD;
      case 1:
        return MUST;
      case 2:
        return MUST_NOT;
      default:
        return null;
    }
  }
}
